#!/usr/bin/env bash

# Copy files to ark VPs
arksync --activity=vrfinder --max-fast-attempts=1 --include=aal-dk,abz2-uk,acc-gh,adl-au,aep-ar,aep2-ar,aep3-ar,agb-de,akl-nz,ams-nl,ams2-nl,ams3-nl,ams7-nl,anr-be,anr2-be,arn-se,asu-py,atl2-us,atl3-us,bcn-es,bdl-us,bed-us,beg-rs,bhd-uk,bjl-gm,bos4-us,bri-it,bud3-hu,bwi-us,bwi3-us,bwy-uk,cbg-uk,cdg-fr,cgh-br,cgs-us,cjj-kr,coo-bj,cph-dk,dal-us,dar-tz,dar2-tz,dbu-us,dca-us,dca3-us,dtw2-us,dub-ie,dub2-ie,dur-za,ens-nl,eug-us,fdh-de,fnl-us,fyv-us,gig-br,ham-de,hel-fi,hkg-cn,hkg3-cn,hlz-nz,hlz2-nz,hnd-jp,iad-us,iad3-us,iev-ua,ind-us,jnb-za,kgl2-rw,las-us,lax3-us,lcy-uk,lcy2-uk,los2-ng,lun-zm,lwc2-us,lwc3-us,mad-es,mhg-de,mnz-us,mru-mu,mry-us,msn3-us,mst-nl,mty-mx,nrt-jp,nrt3-jp,oak5-us,ord-us,ory4-fr,ory5-fr,osl-no,osl2-no,pbh2-bt,per-au,pna-es,poa-br,prg-cz,pry-za,rdu-us,rno-us,rno2-us,san-us,san2-us,san5-us,san7-us,sao-br,scl-cl,scq-es,sdv-il,sea-us,sea2-us,sjc2-us,sjj-ba,sjo-cr,snn-ie,sql-us,syd-au,syd2-au,tij-mx,tlv-il,tnr-mg,tul3-us,txl-de,vko-ru,wbu-us,wlg2-nz,wlg3-nz,yhu-ca,ytz-ca,yul2-ca,yxu-ca,yyc-ca,yyz-ca,zrh-ch,zrh2-ch testaddrs/%MON.addrs %MON:/usr/local/ark/activity/vrfinder/itdk.addrs

# Run scamper on the ark VPs
shmux -c '/usr/local/ark/pkg/scamper-cvs-20181025/bin/scamper -O warts -o itdk.warts -p 50 -c "ping -c 3 -o 1" /usr/local/ark/activity/vrfinder/itdk.addrs >& /dev/null &' -B aal-dk abz2-uk acc-gh adl-au aep-ar aep2-ar aep3-ar akl-nz ams-nl ams2-nl ams3-nl ams7-nl anr-be anr2-be arn-se asu-py atl2-us atl3-us bcn-es bdl-us bed-us beg-rs bhd-uk bjl-gm bos4-us bri-it bud3-hu bwi3-us bwy-uk cbg-uk cdg-fr cgh-br cgs-us cjj-kr coo-bj cph-dk dal-us dar-tz dar2-tz dbu-us dca-us dca3-us dtw2-us dub-ie dub2-ie dur-za ens-nl eug-us fnl-us fyv-us gig-br ham-de hel-fi hkg-cn hkg3-cn hlz-nz hlz2-nz hnd-jp iad-us iad3-us iev-ua ind-us jnb-za kgl2-rw las-us lax3-us lcy-uk lcy2-uk los2-ng lun-zm lwc2-us lwc3-us mad-es mhg-de mnz-us mru-mu mry-us msn3-us mst-nl mty-mx nrt-jp nrt3-jp oak5-us ord-us ory4-fr ory5-fr osl-no osl2-no pbh2-bt per-au pna-es prg-cz pry-za rdu-us rno-us rno2-us san-us san2-us san5-us san7-us sao-br scl-cl scq-es sdv-il sea-us sea2-us sjj-ba sjo-cr snn-ie sql-us syd-au syd2-au tij-mx tlv-il tnr-mg tul3-us txl-de vko-ru wbu-us wlg2-nz yhu-ca ytz-ca yul2-ca yxu-ca yyc-ca yyz-ca zrh-ch zrh2-ch

# Run scamper
/usr/local/ark/pkg/scamper-cvs-20181025/bin/scamper -O warts -o morefour.warts -p 50 -c "ping -c 3 -o 1" /usr/local/ark/activity/vrfinder/all.addrs >& /dev/null &